# Generated by Django 3.1.5 on 2021-01-25 15:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('numero_conta', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nome_usuario', models.CharField(max_length=30)),
                ('saldo', models.DecimalField(decimal_places=2, help_text='Colocar o saldo com 2 casas decimais ex: 10.00', max_digits=20, validators=[django.core.validators.DecimalValidator(decimal_places=2, max_digits=20)])),
            ],
            options={
                'db_table': 'conta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Extrato',
            fields=[
                ('numero_conta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extrato', serialize=False, to='contas.conta')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default='0', max_digits=20)),
                ('saldo_final', models.DecimalField(decimal_places=2, default='0', max_digits=20)),
            ],
            options={
                'db_table': 'extrato',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_transacao', models.CharField(choices=[('debito', 'debito'), ('credito', 'credito')], default='', max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Colocar o valor com 2 casas decimais ex: 10.00', max_digits=20, validators=[django.core.validators.DecimalValidator(decimal_places=2, max_digits=20)])),
                ('data_movimento', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(blank=True, default='', max_length=30)),
                ('numero_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='contas.conta')),
            ],
            options={
                'db_table': 'transacoes',
                'managed': True,
            },
        ),
    ]
